let khodam = [
  "Pensil",
  "Buku",
  "Topi",
  "Gitar",
  "Sepatu",
  "Komputer",
  "Meja",
  "Kucing",
  "Jendela",
  "Mobil",
  "Jam tangan",
  "Kamera",
  "Sepeda",
  "Ponsel",
  "Kunci",
  "Kotak",
  "	Bolpen",
  "	Singa",
  "	Gajah",
  "	Kuda",
  "	Jerapah",
  "	Harimau",
  "	Kucing",
  "	Anjing",
  "	Burung camar",
  "	Belalang",
  "	Ular",
  "	Babi",
  "	Kura-kura",
  "	Kupu-kupu",
  "	Katak",
  "	Buaya",
  "	Zebra",
  "	Burung hantu",
  "	Tupai",
  "	Kanguru",
  "	Koala",
  "	Beruang",
  "	Monyet",
  "	Lumba-lumba",
  "	Ikan paus",
  "	Kepiting",
  "	Kuda laut",
  "	Rajawali",
  "	Kancil",
  "	Kelelawar",
  "	Panda",
  "	Hamster",
  "	Musang",
  "	Lutung",
  "	Burung beo",
  "	Ayam",
  "	Belut",
  "	Laba-laba",
  "	Nyamuk",
  "	Landak",
  "	Gagak",
  "	Burung merak",
  "	Rusa",
  "	Sapi",
  "	Kambing",
  "	Tupai",
  "	Tupai terbang",
  "	Bunglon",
  "	Merpati",
  "	Burung camar",
  "	Ikan hiu",
  "	Lumba-lumba",
  "	Kepiting",
  "	Kura-kura",
  "	Ular",
  "	Kadal",
  "	Bebek",
  "	Elang",
  "	Ayam",
  "	Angsa",
  "	Ikan mas",
  "	Ikan pari",
  "	Gurita",
  "	Siput",
  "	Kuda nil",
  "	Lumba-lumba",
  "	Berang-berang",
  "	Anjing laut",
  "	Kuda laut",
  "	Burung gereja",
  "	Musang",
  "	Rajawali",
  "	Kupu-kupu",
  "	Nuri",
  "	Buaya",
  "	Tikus",
  "	Tupai",
  "	Gajah",
  "	Jerapah",
  "	Kancil",
  "	Kambing",
  "	Harimau",
  "	Singa",
  "	Kucing",
  "	Anjing",
  "	Monyet",
  "	Koala",
  "	Kanguru",
  "	Beruang",
  "	Lutung",
  "	Panda",
  "	Hamster",
  "	Landak",
  "	Burung merak",
  "	Gagak",
  "	Beo",
  "	Rusa",
  "	Sapi",
  "	Ayam",
  "	Tupai terbang",
  "	Bunglon",
  "	Mangga",
  "	Kelapa",
  "	Bambu",
  "	Mawar",
  "	Pisang",
  "	Jambu",
  "	Melati",
  "	Jeruk",
  "	Durian",
  "	Anggrek",
  "	Papaya",
  "	Lidah buaya",
  "	Cempaka",
  "	Terong",
  "	Srikaya",
  "	Jagung",
  "	Labu",
  "	Cabe",
  "	Bunga matahari",
  "	Jati",
  "	Kapas",
  "	Bambu hitam",
  "	Kamboja",
  "	Melon",
  "	Markisa",
  "	Sirsak",
  "	Pala",
  "	Stroberi",
  "	Rambutan",
  "	Salak",
  "	Ketumbar",
  "	Semangka",
  "	Cokelat",
  "	Kelor",
  "	Lobak",
  "	Alpukat",
  "	Bayam",
  "	Sawi",
  "	Kacang hijau",
  "	Kiwi",
  "	Zaitun",
  "	Tomat",
  "	Labu kuning",
  "	Nanas",
  "	Belimbing",
  "	Selada",
  "	Jahe",
  "	Serai",
  "	Bawang merah",
  "	Bawang putih",
  "	Kentang",
  "	Wortel",
  "	Terung",
  "	Kacang panjang",
  "	Kacang tanah",
  "	Kacang kedelai",
  "	Buncis",
  "	Kubis",
  "	Seledri",
  "	Paprika",
  "	Brokoli",
  "	Jeruk nipis",
  "	Lengkuas",
  "	Lada",
  "	Cengkeh",
  "	Cabe merah",
  "	Cabe rawit",
  "	Pakis",
  "	Bambu tali",
  "	Bambu betung",
  "	Bambu haur",
  "	Mahoni",
  "	Angsana",
  "	Aren",
  "	Nangka",
  "	Jarak",
  "	Jarak pagar",
  "	Jarak kepyar",
  "	Kina",
  "	Kenanga",
  "	Kacapiring",
  "	Kacang kedelai",
  "	Kacang kapri",
  "	Kacang tanah",
  "	Ponsel pintar (smartphone)",
  "	Laptop",
  "	Tablet",
  "	Smartwatch",
  "	Komputer desktop",
  "	Televisi",
  "	Kamera digital",
  "	Printer",
  "	Scanner",
  "	Speaker Bluetooth",
  "	Headphone",
  "	Earphone",
  "	Mouse komputer",
  "	Keyboard",
  "	Power bank",
  "	Headset VR (Virtual Reality)",
  "	Drone",
  "	MP3 player",
  "	Konsol permainan (misalnya PlayStation, Xbox)",
  "	Asisten rumah pintar (misalnya Amazon Alexa, Google Home)",
  "	Router",
  "	Modem",
  "	Penguat sinyal Wi-Fi (Wi-Fi extender)",
  "	Kamera CCTV",
  "	Thermostat pintar",
  "	Sikat gigi listrik",
  "	Mesin cukur elektrik",
  "	Tracker kebugaran (fitness tracker)",
  "	Termometer digital",
  "	Monitor tekanan darah",
  "	Ketel listrik",
  "	Rice cooker digital",
  "	Air fryer digital",
  "	Microwave oven digital",
  "	Kulkas pintar",
  "	Mesin cuci pintar",
  "	Mesin pencuci piring pintar",
  "	Pembersih vakum robotik",
  "	Penjernih udara (air purifier)",
  "	Humidifier",
  "	Dehumidifier",
  "	Kipas angin elektrik",
  "	AC (Air Conditioner) pintar",
  "	Sistem pencahayaan pintar",
  "	Skuter listrik",
  "	Sepeda listrik",
  "	Skateboard listrik",
  "	E-book reader (misalnya Kindle)",
  "	Pemutar DVD portabel",
  "	Bingkai foto digital",
  "	Selimut listrik",
  "	Pemantau tidur (sleep tracker)",
  "	Monitor bayi digital",
  "	Pemanas ruangan listrik (fireplace)",
  "	Kursi pijat elektrik",
  "	Mouse gaming",
  "	Keyboard gaming",
  "	Headset gaming",
  "	Monitor gaming",
  "	Kursi gaming (dengan penyesuaian elektronik)",
  "	Timbangan digital (dapur atau kamar mandi)",
  "	Kunci pintu elektronik",
  "	Sistem kamera keamanan (surveillance)",
  "	Pengisi daya surya portabel",
  "	Perangkat GPS genggam",
  "	Bel pintu pintar (smart doorbell)",
  "	Drum elektrik",
  "	Keyboard elektronik (alat musik)",
  "	Kontrol MIDI",
  "	Mixer DJ",
  "	Perekam suara digital",
  "	Proyektor portabel",
  "	Kit mobil Bluetooth",
  "	Radio satelit",
  "	Pencari ikan (fish finder untuk perahu)",
  "	Papan darts elektronik",
  "	Set catur elektronik",
  "	Pembuka botol anggur listrik",
  "	Toilet seat bidet elektronik",
  "	Penangkap serangga elektronik",
  "	Papan skor elektronik",
  "	Pemakanan hewan peliharaan elektronik",
  "	Alat temukan kawat (studi elektronik)",
  "	Stasiun cuaca elektronik",
  "	Sistem pengumpulan tol elektronik (contohnya EZ Pass)",
  "	Kerah anjing elektronik (dengan GPS)",
  "	Pad drum elektronik",
  "	Pencari kunci elektronik",
  "	Permainan Sudoku elektronik",
  "	Penerjemah bahasa elektronik",
  "	Waterpas elektronik (untuk konstruksi)",
  "	Alat pengukur glukosa darah elektronik",
  "	Pelacak hewan peliharaan elektronik",
  "	Pemotong scrapbook elektronik",
  "	Penggiling rempah-rempah elektronik",
  "	Mesin gelembung elektronik",
  "	Tablet gambar elektronik",
  "	Kartu hadiah elektronik",
  "	Pencetak label elektronik",
  "	Pemijat denyut listrik",
];

input.addEventListener("keypress", function (event) {
  if (event.key === "Enter") {
    event.preventDefault();
    document.getElementById("picit").click();
  }
});

function picit() {
  if (document.getElementById("input").value == "") {
    alert("Anda tidak memasukkan apapun!");
  } else {
    let x = document.getElementById("input").value;
    let y = Math.floor(Math.random() * 300);
    document.getElementById("name").innerHTML = x;
    document.getElementById("container").style.display = "none";
    document.getElementById("hasil").style.display = "block";
    document.getElementById("khodam").innerHTML = khodam[(0, y)];

    console.log(y);
  }
}
